"""Initial migration

Revision ID: c146f5647411
Revises: afc9fa36bf0e
Create Date: 2026-01-29 01:40:34.913913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c146f5647411'
down_revision = 'afc9fa36bf0e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
